version: '3.8'
services:
  postgres:
    image: postgres:16-alpine
    container_name: vhandelivery_postgres
    env_file:
      - .env.${NODE_ENV:-development}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  minio:
    image: minio/minio
    container_name: vhandelivery_minio
    env_file:
      - .env.${NODE_ENV:-development}
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_STORAGE_CLASS_STANDARD: 'EC:0'
      MINIO_BROWSER: 'on'
    volumes:
      - ./minio_data:/data
    command: server /data --console-address ":9001"
    restart: always

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    env_file:
      - .env.${NODE_ENV:-development}
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 $${AWS_ACCESS_KEY_ID} $${AWS_SECRET_ACCESS_KEY};
      /usr/bin/mc mb myminio/$${AWS_BUCKET_NAME};
      /usr/bin/mc anonymous set public myminio/$${AWS_BUCKET_NAME};
      exit 0;
      "

  api-service:
    container_name: vhandelivery_api
    build:
      context: .
      dockerfile: Dockerfile.backend
    image: vhandelivery/api-service:latest
    env_file:
      - .env.${NODE_ENV:-development}
    depends_on:
      - postgres
    ports:
      - '3000:3000'

  front-b2b:
    container_name: vhandelivery_front_b2b
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        APP_NAME: front-b2b
    image: vhandelivery/front-b2b:latest
    ports:
      - '4200:80'
    depends_on:
      - postgres

  front-management:
    container_name: vhandelivery_front_management
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        APP_NAME: front-management
    image: vhandelivery/front-management:latest
    ports:
      - '4300:80'
    depends_on:
      - postgres

  front-b2c:
    container_name: vhandelivery_front_b2c
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        APP_NAME: front-b2c
    image: vhandelivery/front-b2c:latest
    ports:
      - '4400:80'
    depends_on:
      - postgres

volumes:
  postgres_data:
