version: '3.8'
services:
  postgres:
    image: postgres:16-alpine
    container_name: vhandelivery_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: vhandelivery_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  minio:
    image: minio/minio
    container_name: vhandelivery_minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
      MINIO_STORAGE_CLASS_STANDARD: "EC:0" 
      MINIO_BROWSER: "on"
    volumes:
      - ./minio_data:/data
    command: server /data --console-address ":9001"
    restart: always

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 admin admin123;
      /usr/bin/mc mb myminio/vhan-media;
      /usr/bin/mc anonymous set public myminio/vhan-media;
      exit 0;
      "

volumes:
  postgres_data:
  minio_data:
