export enum AGENCY_STATUS {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  SUSPENDED = 'SUSPENDED',
}

export const AGENCY_REGISTRATION_OTP = 'AGENCY_REGISTRATION_OTP' as const;
