export const AGENCY_STATUS = {
    PENDING: "PENDING",
    ACTIVE: "ACTIVE",
    INACTIVE: "INACTIVE",
    REJECTED: "REJECTED",
    SUSPENDED: "SUSPENDED"
};

export const AGENCY_REGISTRATION_OTP = 'AGENCY_REGISTRATION_OTP' as const;