export enum AGENCY_STATUS {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum AGENCY_OPERATIONAL_STATUS {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  SUSPENDED = 'SUSPENDED',
  LOCKED = 'LOCKED',
}

export const AGENCY_REGISTRATION_OTP = 'AGENCY_REGISTRATION_OTP' as const;
