export const MERCHANT_STATUS = {
    PENDING: "PENDING",
    ACTIVE: "ACTIVE",
    INACTIVE: "INACTIVE",
    REJECTED: "REJECTED",
    SUSPENDED: "SUSPENDED"
};

export const MERCHANT_REGISTRATION_OTP = 'MERCHANT_REGISTRATION_OTP' as const;
export type MERCHANT_REGISTRATION_OTP_TYPE = typeof MERCHANT_REGISTRATION_OTP;