export enum MERCHANT_STATUS {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export const MERCHANT_REGISTRATION_OTP = 'MERCHANT_REGISTRATION_OTP' as const;
export type MERCHANT_REGISTRATION_OTP_TYPE = typeof MERCHANT_REGISTRATION_OTP;
